name: e2e

on:
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: .nvmrc

      - run: pnpm i

      - run: pnpm -F e2e exec playwright install --with-deps

      - run: pnpm -F e2e run test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: packages/e2e/playwright-report/
          retention-days: 30

      - uses: daun/playwright-report-summary@v3
        if: ${{ !cancelled() }}
        with:
          report-file: packages/e2e/playwright-report/results.json
